<?php
/**
 * Magento
 * @category    design
 * @package     base_default
 */
?>

<?php
$_code = $this->getMethodCode();
?>

<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;padding: 0px;" >
    <li style="font-weight: bold;">
        Pague seguro ahora en el banco de su preferencia:
        <ul style="list-style: initial; padding-left: 36px; line-height: 12px; margin-top: 4px; font-weight: normal;">
            <li>Banca Electrónica</li>
            <li>Agentes</li>
            <li>Ventanilla</li>
        </ul>
    </li>
</ul>

