<?php
/**
 * Magento
 *
 * @category    design
 * @package     base_default
 *
 *
 */
?>
<img src="<?php echo Mage::getBaseUrl('skin').'frontend/spago/default/images/sp_logo.png'; ?> " alt="SeguriPago" height="30" border="0" style="margin-left: 2px;">
<img src="<?php echo Mage::getBaseUrl('skin').'frontend/spago/default/images/visa40x90 2.jpg'; ?>"  alt="Visa" height="30" border="0" style="margin-left: 2px;">
<img src="<?php echo Mage::getBaseUrl('skin').'frontend/spago/default/images/matercard_90x40.jpg'; ?>"  alt="Mastercard" height="30" border="0" style="margin-left: 2px;">
</label>
<label>
<div style="height: 400px !important;">
    <img src="<?php echo Mage::getBaseUrl('skin').'frontend/spago/default/images/bbva_90X40.jpg'; ?> " alt="BBVA" height="30" border="0" style="margin-left: 2px;">
    <img src="<?php echo Mage::getBaseUrl('skin').'frontend/spago/default/images/scotia_90X40.jpg';  ?> " alt="Scotiabank" height="30" border="0" style="margin-left: 2px;">
    <img src="<?php echo Mage::getBaseUrl('skin').'frontend/spago/default/images/bcp_90X40.jpg';  ?> " alt="BCP" height="30" border="0" style="margin-left: 2px;">
</div>