
<?php 
    $count_labels = 0;
	$sale = false;
	if (themeOptions('sale_label'))
	{
		$specialPrice = number_format($_product->getFinalPrice(), 2);
		$regularPrice = number_format($_product->getPrice(), 2);
		if ($specialPrice != $regularPrice){
            $count_labels++;
	       	$sale = true;
		}
	}
    
	$new = false;
	if (themeOptions('new_label'))
	{
        $now = date("Y-m-d H:m:s");   
        $newFromDate = $_product->getNewsFromDate();
        $newToDate = $_product->getNewsToDate();          

        if (!$newFromDate && !$newToDate)
            $new = false;
        else if (!$newFromDate || $newFromDate < $now)
            $new = (!$newToDate || $newToDate > $now);
	}
    
    if($new){
        $count_labels++;
        ?>
            <div class="newproduct_grid"><?php echo $this->__('New') ?></div>
        <?php
    }
    
    if($sale){
        ?>
            <div class="saleproduct <?php if($count_labels == 1) echo 'once' ?>"><?php echo $this->__('Sale') ?></div>
        <?php
    }
?>