<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
    $now = date("Y-m-d H:m:s");     
    $use_zoom = themeOptions('use_zoom'); 
    $use_carousel = themeOptions('use_carousel');
    $_layout = themeOptions('layout'); 
    $thumbs_count = count($this->getGalleryImages());
    $_i_thumbs = 0;
?>
<?php 
    switch($_layout){
        case 'horizontal':
            $_mainWidth = 483;
            $_mainHeight = 398;
            $_smWidth = 68;
            $_smHeight = 68;
//            $_carWidth = 80;
            $_zoomLeft = $_mainWidth + 17;
            $_zoomWidth = 80;
        break;
        case 'vertical':
            $_mainWidth = 328;
            $_mainHeight = 398;
            $_smWidth = 68;
            $_smHeight = 68;
            $_carWidth = 258;
            $_zoomLeft = $_mainWidth + 17;
            $_zoomWidth = 450;
        break;
        default:
            $_mainWidth = 338;
            $_mainHeight = 338;
            $_smWidth = 68;
            $_smHeight = 68;
            $_carWidth = 244;
            $_zoomLeft = $_mainWidth + 17;
            $_zoomWidth = 536;        
        break;
    }
?>
<style>
    .product-view .product-img-box .more-views { width:<?php echo $_carWidth ?>px; }
    #zoom-window { left: <?php echo $_zoomLeft ?>px; width: <?php echo $_zoomWidth ?>px; }
</style>
<div class="zoom-container layout_<?php echo $_layout ?>">
    
    <?php include('labels.phtml') ?>
   
    <div class="even-more-views show-responsive-grid" >
       
        <?php foreach ($this->getGalleryImages() as $_image): $_i_thumbs++; ?>
                <?php if ($this->isGalleryImageVisible($_image)): ?>
                <div class="slide-vert" <?php 
                switch ($thumbs_count ) {
                    case 1: echo 'style="width:25%;"';
                        break; 
                    case 2: echo 'style="width:25%;"';
                        break;
                    case 3: echo 'style="width:25%;"';
                        break;
                    case 4: echo 'style="width:25%;"';
                        break;
                    case 5: echo 'style="width:20%;"';
                        break;
                    case 6: echo 'style="width:16.66%;"';
                        break;
                    case 7: echo 'style="width:14.28%;"';
                        break;
                }
        ?>>
                    <a class="zoom-thumbnail<?php if(!$use_zoom): ?> lightbox<?php endif;?>"  href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()); ?>" data-easyzoom-source="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize($_mainWidth,$_mainHeight); ?>" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize($_smWidth,$_smHeight); ?>" width="<?php echo $_smWidth ?>" height="<?php echo $_smHeight ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" /></a>
                </div>
                <?php endif;?>
        <?php endforeach; ?>
        
        
    </div>
    
    <div class="more-views  hide-responsive-grid"
        <?php if($use_carousel && $thumbs_count > 4): ?>style="height:auto;"<?php endif; ?>>
        <div class="zoom-gallery slider">
        <?php if($thumbs_count == 0): ?>
            <div class="slide last">
                <a class="zoom-thumbnail<?php if(!$use_zoom): ?> lightbox<?php endif;?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'image') ?>" data-easyzoom-source="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize($_mainWidth,$_mainHeight) ?>">
                    <?php
                        $_img = '<img class="zoom-image" src="'.$this->helper('catalog/image')->init($_product, 'thumbnail')->resize($_smWidth,$_smHeight).'" width="'.$_smWidth.'" height="'.$_smHeight.'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
                        echo $_helper->productAttribute($_product, $_img, 'image');
                    ?>
                </a>   
            </div>   
        <?php endif; ?>
        <?php if ($thumbs_count > 0): ?>  
            <?php foreach ($this->getGalleryImages() as $_image): $_i_thumbs++; ?>
                <?php if ($this->isGalleryImageVisible($_image)): ?>
                <div class="slide <?php if($thumbs_count == $_i_thumbs) echo 'last'; ?>">
                    <a class="zoom-thumbnail<?php if(!$use_zoom): ?> lightbox<?php endif;?>"  href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()); ?>" data-easyzoom-source="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize($_mainWidth,$_mainHeight); ?>" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize($_smWidth,$_smHeight); ?>" width="<?php echo $_smWidth ?>" height="<?php echo $_smHeight ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" /></a>
                </div>
                <?php endif;?>
            <?php endforeach; ?>
        <?php endif; ?>
        </div>              
    </div>
            
    <div class="main-image" >   		
       <a id="zoom" class="<?php if(!$use_zoom): ?> lightbox<?php endif;?> main-thumbnail" href="<?php echo $this->helper('catalog/image')->init($_product, 'image') ?>">		
           <?php		
                $_img = '<img class="zoom-image" src="'.$this->helper('catalog/image')->init($_product, 'image')->resize($_mainWidth,$_mainHeight).'" width="'.$_mainWidth.'" height="'.$_mainHeight.'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';		
               echo $_helper->productAttribute($_product, $_img, 'image');		
           ?>		
       </a> 		
       <?php if($use_zoom): ?>		
       <div class="lightbox-btn">		
           <a id="zoom" class="lightbox" href="<?php echo $this->helper('catalog/image')->init($_product, 'image') ?>">		
                <?php echo $this->__('Enlarge') ?>		
           </a>        		
       </div>		
       <?php endif;?>		
   </div> 
<!--    <div class="main-image easyzoom--adjacent " >   
        <a id="zoom" class="<?php if(!$use_zoom): ?> lightbox<?php endif;?> main-thumbnail" href="<?php echo $this->helper('catalog/image')->init($_product, 'image') ?>">
            <?php
                $_img = '<img class="zoom-image" src="'.$this->helper('catalog/image')->init($_product, 'image')->resize($_mainWidth,$_mainHeight).'" width="'.$_mainWidth.'" height="'.$_mainHeight.'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
                echo $_helper->productAttribute($_product, $_img, 'image');
            ?>
        </a> 
        <?php if($use_zoom): ?>
        <div class="lightbox-btn">
            <a id="zoom-lightbox" class="lightbox" href="<?php echo $this->helper('catalog/image')->init($_product, 'image') ?>">
                <?php echo $this->__('Enlarge') ?>
            </a>        
        </div>
        <?php endif;?>

    </div> 
-->            	
       <?php
        $_producto = $this->getProduct();
        $_products_id = $_producto->getRelatedProductIds();
        if(count($_products_id)>0){
       ?>
        <div class="referal-products" <?php 
                switch ($thumbs_count ) {
                    case 1: echo 'style="width:25%;"';
                        break; 
                    case 2: echo 'style="width:25%;"';
                        break;
                    case 3: echo 'style="width:25%;"';
                        break;
                    case 4: echo 'style="width:25%;"';
                        break;
                    case 5: echo 'style="width:20%;"';
                        break;
                    case 6: echo 'style="width:16.66%;"';
                        break;
                    case 7: echo 'style="width:14.28%;"';
                        break;
                }
        ?>>
       <?php
            foreach ($_products_id as $_item ) {
              $obj = Mage::getModel('catalog/product');        
              $_products = $obj->load($_item);                
       ?>
              <a href="<?php echo $_products->getProductUrl() ?>">
              <img src="<?php echo $_products->getImageUrl() ?>" height='auto'/></a>
            <?php } ?>
        </div>
        <?php }?>
    
<?php switch($_layout){
        case 'horizontal':
            if($use_carousel && $thumbs_count > 5): ?>
<!--				<div class="more-views-arrow prev">&nbsp;</div>
				<div class="more-views-arrow next">&nbsp;</div>                 -->
			<?php endif; 
        break;
        case 'vertical':
            if($use_carousel && $thumbs_count == 4): ?>
<!--				<div class="more-views-arrow prev thumbs-count-4">&nbsp;</div>
				<div class="more-views-arrow next thumbs-count-4">&nbsp;</div>                 -->
			<?php else:
			{if($use_carousel && $thumbs_count > 3): ?>
<!--				<div class="more-views-arrow prev">&nbsp;</div>
				<div class="more-views-arrow next">&nbsp;</div>                 -->
			<?php endif;} endif; 			
        break;
		default:
             if($use_carousel && $thumbs_count > 4): ?>
<!--				<div class="more-views-arrow prev">&nbsp;</div>
				<div class="more-views-arrow next">&nbsp;</div>                 -->
            <?php endif;    
        break;
    }?>
 
	
<!--<?php if($use_carousel && $thumbs_count > 2): ?>
        <div class="mob-more-views-arrow prev">&nbsp;mob-more-views-arrow prev</div>
	<div class="mob-more-views-arrow next">&nbsp;mob-more-views-arrow next</div>                 
<?php endif; ?>
-->
</div>    
    
	<script type="text/javascript">    
    	
    <?php if($use_zoom): ?>
        // Start easyZoom
    	// jQuery('#zoom')
    	// 	.easyZoom({
    	// 		parent: 'div.zoom-container',
    	// 		preload: '',
     //            lightboxBtn: '.lightbox-btn .lightbox'
    	// 	})
    	// 	.data('easyZoom')
    	// 	.gallery('a.zoom-thumbnail');
        blancoTheme.initZoom($j('.main-image'), $j(".zoom-gallery"));
    <?php endif;?>
    
    <?php if($use_carousel && $thumbs_count > 2): ?>	 
        jQuery('.more-views').iosSlider({
            desktopClickDrag: true,
            snapToChildren: true,
            infiniteSlider: false,
            navNextSelector: '.mob-more-views-arrow.next ,.more-views-arrow.next',
            navPrevSelector: '.mob-more-views-arrow.prev ,.more-views-arrow.prev'
        });                         
    <?php endif;?>
    
     // Start lightbox
    jQuery('a.lightbox').lightBox({
        imageLoading    : '<?php echo $this->getSkinUrl('images/lightbox-ico-loading.gif') ?>',
        imageBtnClose   : '<?php echo $this->getSkinUrl('images/lightbox-btn-close.gif') ?>',
        imageBtnNext    : '<?php echo $this->getSkinUrl('images/lightbox-btn-next.gif') ?>',
        imageBtnPrev    : '<?php echo $this->getSkinUrl('images/lightbox-btn-prev.gif') ?>',
        imageBlank      : '<?php echo $this->getSkinUrl('images/lightbox-blank.gif') ?>',
        fixedNavigation : true
    });        
	</script>   
<?php echo $this->getChildHtml('after'); ?>