<div class="main-section-separation margin-top-fix">		
    <div class="thin"></div>		
    <div class="tick"></div>		
</div>

<div class="footer-container2">
    <div class = "footer-top">
        <div class = "footer-top-left">
            <h2 class="footer-title2">Mi Cuenta</h2>
            <ul class="footer-list">
                <li>Registrate</li>
                <li>Iniciar Sesión</li>
                <li>Recuperar Contraseña</li>
                <li>Pedidos</li>
            </ul>
        </div>
        <div class = "footer-top-center">
            <h2 class="footer-title2">Acerca Bruno Ferrini</h2>
            <ul class="footer-list">
                <li>Historia</li>
                <li>Terminos y Condiciones</li>
                <li>Nuestras Tiendas</li>
                <li>Trabaja con Nosotros</li>
            </ul>
        </div>
        <div class = "footer-top-right">
            <h2 class="footer-title2">Servicio al Cliente</h2>
            <ul class="footer-list">
                <li>Politicas de Garantía y Devolución</li>
                <li>Privacidad</li>
                <li>Contactanos</li>
                <li>Preguntas Frecuentes</li>
                <li>Libro de Reclamaciones</li>
            </ul>
        </div>
    </div>
     <div class="full-width footer-links">
        <?php echo $this->getCopyright() ?>&nbsp;&nbsp;
    </div>
         
         
</div>  
<!--    <div class="footer">
        <?php echo $this->getChildHtml('bottomContainer') ?>
        <div class="f-left">
            <?php echo $this->getChildHtml('footer_links') ?><br />
            <?php echo $this->getCopyright() ?>&nbsp;&nbsp;
            <?php echo $this->getChildHtml('cms_footer_links') ?>
        </div>
        <div class="f-right">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('verify')->toHtml(); ?>
        </div>
    </div>-->
