

<div class="center-container">
    <div class="header-list-container">
        <h2>Invierno</h2>
        <ul>
            <li>Novedades</li>
            <li>Botas</li>
            <li>Invierno</li>
        </ul>
        <h2>Oficina</h2>
        <ul>
            <li>Mocasines</li>
            <li>Tacos</li>
            <li>Bajos</li>
        </ul>
        <h2>Casual</h2>
        <ul>
            <li>Deportivo</li>
            <li>Fiesta</li>
            <li>Caminante</li>
        </ul>
    </div>
    <div class="iosSlider"><!-- slider -->
        <div class="slider"><!-- slides -->
            <div class="slide"><img class="royalImage" alt="" src="{{media url="wysiwyg/blanco/banner-1.png"}}" /></div>
            <div class="slide"><img class="royalImage" alt="" src="{{media url="wysiwyg/blanco/banner-2.png"}}" /></div>
            <div class="slide"><img class="royalImage" alt="" src="{{media url="wysiwyg/blanco/banner-3.png"}}" /></div>
            <div class="slide"><img class="royalImage" alt="" src="{{media url="wysiwyg/blanco/banner-4.jpg"}}" /></div>
        </div>
        <div class="sliderNavi"><span class="naviItem selected">1</span> <span class="naviItem">2</span> <span class="naviItem">3</span> <span class="naviItem">4</span></div>
    </div>
    <div class="top-banner-holder hide-responsive">
        <div class="home-text"><img alt="" src="{{media url="wysiwyg/blanco/b1.jpg"}}" /><a class="readmore" href="/demo/blanco/man.html">Shop Now</a></div>
        <div class="home-text "><img alt="" src="{{media url="wysiwyg/blanco/b2.jpg"}}" /><a class="readmore" href="/demo/blanco/accessories.html">Shop Now</a></div>
    </div>
</div>
<div class="clear">
    <h5 class="home-section-separation">&nbsp;</h5>
    <div class="clear" style="border-top: 1px solid #EFEFEF; height: 13px;">&nbsp;</div>
    {{block type="catalog/product_list" column_count="4" category_id="7" template="catalog/product/list_home.phtml"}}</div>
<div class="clear">
    <h5 class="home-section-separation">&nbsp;</h5>
    <div class="clear" style="border-top: 1px solid #EFEFEF; height: 13px;">&nbsp;</div>
    <div class="brand-image b1" style="background-image: url('{{media url="wysiwyg/blanco//marca-1.png"}}');">&nbsp;</div>
    <div class="brand-image b2" style="background-image: url('{{media url="wysiwyg/blanco//marca-2.png"}}');">&nbsp;</div>
    <div class="brand-image b3" style="background-image: url('{{media url="wysiwyg/blanco//marca-3.png"}}');">&nbsp;</div>
    <div class="brand-image b4" style="background-image: url('{{media url="wysiwyg/blanco//marca-4.png"}}');">&nbsp;</div>
</div>
<div class="clear">
    {{block type="catalog/product_list" column_count="4" category_id="7" template="catalog/product/special.phtml"}}
</div>

<div class="clear">
    {{block type="catalog/product_list" column_count="4" category_id="7" template="catalog/product/special.phtml"}}
</div>